-- Removendo campos de endereco
ALTER TABLE gastrosphere.addresses
ADD COLUMN number VARCHAR(10) DEFAULT 'N/A' NOT NULL,
ADD COLUMN complement VARCHAR(255),
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
